#Iniciar os Containers do docker(Pode demorar um pouco na primeira vez):
#docker-compose up -d

#Pausar o Docker:
#docker-compose down

#Pausar o Docker para atualização de versão do banco de db_siged:
#docker-compose down -v

#Reconstruir Docker
#docker-compose up -d --build --force-recreate --no-deps

version: '3.3'

services:
  www:
    #Caminho do Dockerfile para cnstrução do container do PHP e Apache
    build: .
    ports: 
      - "8082:80"
